export type DiagramId = 'directions' | 'planes' | 'lobes' | 'meninges' | 'brain' |
  'sternum' | 'atlas' | 'arm' | 'pelvis' | 'joints' | 'disc' | 'cruciates' |
  'menisci' | 'quadriceps';
export type Tip = {
  id: string; title: string; answer?: string; cue: string; kind: string;
  recognition?: string | string[]; trap?: string; diagram?: DiagramId;
  image?: { src: string; alt: string; caption: string; width: number; height: number };
  comparison?: { headers: string[]; rows: string[][] };
  sources: string[];
};
export type TipGroup = { id: string; title: string; intro: string; tips: Tip[] };
export const tipGroups: TipGroup[] = [
  { id: 'linguagem', title: 'Nomes, posições e cortes',
    intro: 'A referência é sempre o corpo em posição anatômica: em pé, palmas para a frente.',
    tips: [
      { id: 'lobo-polo', title: 'Lobo e polo: região ou ponta?',
        answer: 'Lobo é uma subdivisão de um órgão, frequentemente delimitada por sulcos ou fissuras. Polo é uma extremidade. No telencéfalo, o lobo frontal ocupa uma região; o polo frontal é sua ponta anterior.',
        cue: 'Polo Norte e Polo Sul são extremos. Use a mesma ideia no órgão.',
        kind: 'Associação espacial', trap: '“Lobo é maior” ajuda, mas tamanho sozinho não define lobo. Polo não é outro lobo.',
        sources: ['brain'] },
      { id: 'temporal', title: 'Temporal: onde fica?',
        answer: 'Temporal remete à região da têmpora, na lateral da cabeça. O osso temporal fica próximo da orelha; o lobo temporal fica lateralmente, abaixo do sulco lateral; o músculo temporal ocupa a fossa temporal.',
        cue: 'Encoste na têmpora. O nome já entrega o endereço.', kind: 'Nome + gesto',
        recognition: 'No cérebro, procure a porção lateral inferior. No crânio, a região da orelha.',
        sources: ['skull', 'brain'] },
      { id: 'occipital', title: 'Occipital: atrás da cabeça',
        answer: 'A região occipital é posterior. O osso occipital forma parte de trás e da base do crânio; o lobo occipital ocupa a região posterior do telencéfalo.',
        cue: 'Leve a mão à parte de trás da cabeça: essa é sua referência occipital.',
        kind: 'Gesto', diagram: 'lobes',
        trap: 'O cerebelo fica abaixo do lobo occipital, mas é uma estrutura diferente.',
        sources: ['skull', 'brain'] },
      { id: 'parietal', title: '“Pariental”? O nome é parietal',
        answer: 'Parietal vem da ideia de parede. Os ossos parietais formam boa parte do teto e das paredes laterais do crânio. O lobo parietal fica atrás do sulco central. Nas membranas serosas, parietal indica a camada que reveste a parede da cavidade.',
        cue: 'Parietal → parede. Visceral → víscera.', kind: 'Significado do nome',
        trap: 'O sentido depende da estrutura: osso parietal, lobo parietal e pleura parietal não são a mesma coisa.',
        sources: ['terms', 'skull', 'brain'] },
      { id: 'medial-lateral', title: 'Medial e lateral: perto de quê?',
        answer: 'Medial é mais próximo do plano mediano; lateral é mais afastado dele. Compare estruturas: o nariz é medial aos olhos e as orelhas são laterais aos olhos.',
        cue: 'Medial aproxima do meio. Lateral vai para os lados.', kind: 'Associação espacial',
        diagram: 'directions', trap: 'Medial não significa “à esquerda”. Há estruturas mediais dos dois lados.',
        sources: ['terms'] },
      { id: 'mediano', title: 'Mediano não é a mesma coisa que medial',
        answer: 'Mediano indica o meio. O plano mediano atravessa a linha central e separa metades direita e esquerda. O nervo mediano recebe um nome associado à posição e segue pelo membro superior, passando pelo túnel do carpo.',
        cue: 'Mediano: no meio. Medial: mais perto do meio, em comparação com algo.',
        kind: 'Comparação', trap: 'O nervo mediano não passa no plano mediano do corpo e não está sempre no centro geométrico do braço.',
        sources: ['terms'] },
      { id: 'radial', title: 'Radial: o lado do polegar',
        answer: 'Radial significa relativo ao rádio. No antebraço em posição anatômica, o rádio é lateral, do lado do polegar; a ulna é medial, do lado do dedo mínimo.',
        cue: 'Faça um “joinha”: o polegar aponta o lado do rádio. Um relato de aluno registra o uso de “All right, radius!” com esse gesto.',
        kind: 'Macete relatado em aula',
        trap: 'A regra localiza o osso. O nervo radial tem um trajeto próprio, não acompanha o rádio inteiro.',
        sources: ['arm', 'thumb'] },
      { id: 'coronal', title: 'Corte coronal = frente e costas',
        answer: 'O plano coronal, ou frontal, é vertical e separa porções anterior e posterior. É paralelo à fronte. Um corte coronal permite olhar uma fatia de frente.',
        cue: 'Lembre da parte da coroa que atravessa a testa de uma orelha à outra. Prolongue essa faixa para baixo.',
        kind: 'Associação visual', diagram: 'planes',
        trap: 'A coroa inteira é um anel: não use o anel horizontal para lembrar o plano. Coronal é vertical.',
        sources: ['terms'] },
      { id: 'sagital', title: 'Corte sagital = direita e esquerda',
        answer: 'Planos sagitais são verticais e separam porções direita e esquerda. O sagital mediano passa exatamente pelo meio; os demais planos sagitais são paralelos a ele.',
        cue: 'Imagine uma divisória vertical passando pelo nariz e pela nuca: fica um lado direito e outro esquerdo.',
        kind: 'Associação visual', trap: 'Só o plano mediano divide o corpo em metades. Sagital não é sinônimo de mediano em todos os casos.',
        sources: ['terms'] },
    ] },
  { id: 'nervoso', title: 'Encéfalo e meninges',
    intro: 'Primeiro localize a estrutura; depois confira a textura e os acidentes anatômicos.',
    tips: [
      { id: 'meninges', title: 'Dura, aracnoide e pia: a ordem das capas',
        answer: 'De fora para dentro: dura-máter, aracnoide-máter e pia-máter. Dura é resistente; aracnoide passa sobre os sulcos e tem trabéculas semelhantes a teias; pia acompanha intimamente a superfície, entrando nos sulcos.',
        cue: 'PAD: Pia, Aracnoide, Dura, de dentro para fora. O trocadilho inglês “meninges PAD the brain” compara as meninges a um acolchoamento. Para entrar no crânio, inverta: D–A–P.',
        kind: 'Macete universitário documentado', diagram: 'meninges',
        trap: 'PAD começa junto ao tecido nervoso. Na ordem externa → interna, a primeira é a dura.',
        sources: ['meninges', 'pad', 'padLayers'] },
      { id: 'leptomeninge', title: 'Leptomeninge: duas meninges finas',
        answer: 'Leptomeninges é o nome coletivo de aracnoide + pia. Lepto significa fino. A dura é a meninge espessa, também chamada paquimeninge. O conjunto também é chamado pia-aracnoide.',
        cue: 'Lepto = fino: junte as duas fininhas, aracnoide e pia.', kind: 'Significado do nome',
        trap: 'Não é uma quarta meninge.', sources: ['meninges'] },
      { id: 'pia-aracnoide', title: 'Aracnoide e pia são inseparáveis?',
        answer: 'São distintas e ligadas por trabéculas. Entre elas existe o espaço subaracnóideo, com líquor e vasos. A pia acompanha os sulcos; a aracnoide passa por cima deles. O nome coletivo não elimina esse espaço.',
        cue: 'Teia faz pontes; pia acompanha o relevo.',
        kind: 'Comparação visual',
        recognition: 'Na peça, a película delicada pode ser difícil de separar ou estar danificada. Confira a exposição da peça e o relevo da superfície.',
        trap: 'Não memorize “coladas, sem espaço”. Leptomeninge é um conjunto, não uma fusão sem intervalo.',
        sources: ['meninges'] },
      { id: 'divisoes-encefalo', title: 'Telencéfalo, diencéfalo e cerebelo',
        image: { src: 'encefalo-divisoes.png', width: 1172, height: 1081,
          alt: 'Corte sagital do encéfalo com telencéfalo, diencéfalo, mesencéfalo, ponte, bulbo, cerebelo e medula espinal identificados.',
          caption: 'Localização das divisões do encéfalo em corte sagital.' },
        answer: 'Telencéfalo: os grandes hemisférios com giros, sulcos e lobos. Diencéfalo: região profunda, com tálamo e hipotálamo, melhor vista em corte mediano. Cerebelo: posterior ao tronco, abaixo da região occipital, com folhas estreitas.',
        cue: 'Telencéfalo por fora; diencéfalo profundo; cerebelo atrás e embaixo.',
        kind: 'Mapa de posição', diagram: 'brain',
        recognition: 'Cerebelo tem sulcos finos e repetidos; em corte, sua substância branca lembra uma árvore. Telencéfalo tem giros mais largos.',
        trap: 'Encéfalo é o conjunto. Na divisão usada em anatomia, cérebro reúne telencéfalo e diencéfalo; cerebelo e tronco são outras partes do encéfalo.',
        sources: ['brain'] },
      { id: 'tronco', title: 'Tronco encefálico: mesencéfalo, ponte e bulbo',
        answer: 'De cima para baixo: mesencéfalo → ponte → bulbo → medula espinal. O tronco fica à frente do cerebelo. A ponte é a saliência ventral mais volumosa; o bulbo é inferior e afunila em direção à medula.',
        cue: 'Use a ponte como ponto de partida: mesencéfalo acima, bulbo abaixo.',
        kind: 'Referência na peça',
        recognition: 'Mesencéfalo: pedúnculos cerebrais na face ventral e quatro colículos na dorsal. Ponte: abaulamento e sulco basilar ventral. Bulbo: pirâmides e olivas ventrais. Cerebelo: folhas transversais, fora do tronco.',
        trap: 'Não confunda pedúnculos cerebrais com cerebelares. Em peça isolada, confira se está vendo a face ventral ou dorsal.',
        sources: ['brain'] },
    ] },
  { id: 'ossos', title: 'Ossos: reconhecer pela peça',
    intro: 'Um detalhe característico costuma ajudar mais do que decorar a silhueta inteira.',
    tips: [
      { id: 'esterno', title: 'Esterno: cabo, lâmina e ponta',
        image: { src: 'esterno-partes.png', width: 542, height: 850,
          alt: 'Esterno em vista anterior, com manúbrio, corpo do esterno e processo xifoide identificados.',
          caption: 'De cima para baixo: manúbrio, corpo do esterno e processo xifoide.' },
        answer: 'De cima para baixo: manúbrio do esterno, corpo do esterno e processo xifoide. Manúbrio é a porção superior mais larga; corpo é alongado; xifoide é a pequena extremidade inferior.',
        cue: 'Veja uma espada: o manúbrio é o cabo, o corpo é a lâmina e o xifoide é a ponta.',
        kind: 'Analogia de forma', diagram: 'sternum',
        trap: 'O xifoide varia de forma: pode ser bifurcado ou curvo. A posição inferior é mais segura que a aparência de “ponta”.',
        sources: ['sternum'] },
      { id: 'atlas', title: 'C1 é Atlas: o anel que sustenta o crânio',
        answer: 'Atlas é a primeira vértebra cervical. Tem arcos anterior e posterior e massas laterais; não tem corpo vertebral nem processo espinhoso típico. Suas faces superiores recebem os côndilos do occipital.',
        cue: 'Atlas da mitologia sustenta o céu; Atlas da coluna sustenta a cabeça. Occipital + C1 fazem principalmente o gesto do “sim”.',
        kind: 'Mitologia + gesto',
        trap: 'C1 sustenta o crânio, não toca nem “segura” diretamente o cérebro. Na mitologia, Atlas sustenta o céu; a imagem de um globo é uma associação popular.',
        sources: ['spine', 'yes'] },
      { id: 'axis', title: 'C2 é Áxis: procure o dente',
        image: { src: 'c2_den_c1.jpg', width: 1280, height: 707,
          alt: 'Atlas (C1) sobre o áxis (C2), com o dente do áxis projetando-se para cima dentro do anel do atlas.',
          caption: 'C1 sobre C2: o dente do áxis sobe dentro do anel do atlas.' },
        answer: 'O áxis tem uma projeção superior chamada dente do áxis, ou processo odontoide. O dente articula com a face interna do arco anterior de C1 e fica contido pelo ligamento transverso do atlas.',
        cue: 'Áxis lembra eixo. Seu dente é o pivô em torno do qual atlas e cabeça giram: o gesto do “não”.',
        kind: 'Nome + movimento',
        recognition: 'C1: anel, sem corpo. C2: corpo + dente que sobe. O dente não é o processo espinhoso.',
        trap: 'Não imagine o dente preenchendo o forame inteiro de C1: a medula passa atrás dele, separada pelo ligamento transverso.',
        sources: ['spine', 'no'] },
      { id: 'ulna-radio-umero', title: 'Úmero, ulna e rádio: braço ou antebraço?',
        answer: 'Úmero fica no braço, entre ombro e cotovelo. Ulna e rádio ficam no antebraço. Com as palmas para a frente, rádio é lateral (polegar) e ulna é medial (dedo mínimo).',
        cue: 'Joinha para achar o rádio; ponta do cotovelo para achar a ulna.',
        kind: 'Gesto + acidente ósseo', diagram: 'arm',
        recognition: 'Úmero: cabeça arredondada grande na extremidade proximal. Ulna: olécrano e incisura troclear em gancho no cotovelo. Rádio: cabeça proximal em disco e extremidade distal larga.',
        trap: 'Ao virar a palma para trás (pronação), o rádio cruza a ulna. A regra lateral/medial usa a posição anatômica.',
        sources: ['arm'] },
      { id: 'quadril', title: 'Ílio, ísquio e púbis: asa, assento e frente',
        image: { src: 'pelve-ilio-isquio-e-pubis.png', width: 768, height: 373,
          alt: 'Pelve com ílio em vermelho, ísquio em verde e púbis em amarelo, com os acetábulos indicados.',
          caption: 'Ílio, ísquio e púbis destacados por cores, com os acetábulos indicados.' },
        answer: 'Cada osso do quadril adulto reúne três partes fusionadas. Ílio é a grande porção superior, com a crista ilíaca. Ísquio fica posteroinferiormente. Púbis fica anteroinferiormente e encontra o púbis do outro lado na sínfise.',
        cue: 'Ílio: a asa. Ísquio: onde você senta. Púbis: a frente da pelve.',
        kind: 'Forma + função',
        recognition: 'Ache o acetábulo: as três partes participam dele. Ache o forame obturado: púbis e ísquio formam suas bordas. O túber isquiático é a saliência de apoio ao sentar.',
        trap: 'Ílio (osso) e íleo (intestino) são palavras diferentes. Osso do quadril não é só o ílio.',
        sources: ['pelvis'] },
      { id: 'lambdoidea', title: 'Sutura lambdóidea: desenhe um Λ',
        answer: 'A sutura lambdóidea separa os parietais do occipital na parte posterior do crânio. Seu nome remete à letra grega lambda maiúscula, Λ, semelhante a um V invertido.',
        cue: 'Lambda → Λ → lambdóidea. Na peça, procure atrás, entre parietais e occipital.',
        kind: 'Nome + forma',
        recognition: 'Sagital: entre os dois parietais. Coronal: entre frontal e parietais. Lambdóidea: entre parietais e occipital.',
        trap: 'As bordas são serrilhadas e variáveis: o Λ é o trajeto geral, não uma linha perfeitamente reta.',
        sources: ['skull'] },
    ] },
  { id: 'articulacoes', title: 'Articulações e joelho',
    intro: 'Pergunte o que une as peças e se existe uma cavidade articular.',
    tips: [
      { id: 'tipos-articulacao', title: 'Fibrosa, cartilaginosa ou sinovial?',
        answer: 'Fibrosa: união por tecido conjuntivo fibroso, sem cavidade sinovial. Cartilaginosa: união por cartilagem, sem cavidade sinovial. Sinovial: cavidade com líquido sinovial, cápsula e cartilagem articular.',
        cue: 'Fibrosa tem fibras; cartilaginosa tem cartilagem unindo; sinovial tem espaço com líquido.',
        kind: 'Critério de classificação', diagram: 'joints',
        recognition: 'Fibrosas: suturas, sindesmoses e gonfoses. Cartilaginosas: sincondroses (hialina) e sínfises (fibrocartilagem). Sinoviais: ombro, joelho, ATM.',
        trap: '“Sinóvia” é o líquido, não o nome da classe. Ter cartilagem não basta para ser cartilaginosa: sinoviais também têm cartilagem articular.',
        sources: ['fibrous', 'cartilage', 'synovial'] },
      { id: 'gonfose-sindesmose', title: 'Gonfose e sindesmose: dente ou amarra?',
        answer: 'Gonfose é a união da raiz do dente ao alvéolo pelo ligamento periodontal. Sindesmose une ossos por ligamentos ou membrana interóssea, como entre rádio e ulna ou entre tíbia e fíbula.',
        cue: 'Gonfose: pino no encaixe, como a raiz no alvéolo. Sindesmose: duas peças amarradas por uma faixa ou membrana.',
        kind: 'Analogia estrutural',
        trap: 'Ambas são fibrosas. Dente não é osso; ainda assim, sua união ao alvéolo é uma articulação. A grafia é sindesmose.',
        sources: ['fibrous'] },
      { id: 'disco', title: 'Disco intervertebral: o donut recheado',
        answer: 'Os dois componentes principais são anel fibroso, periférico e resistente, e núcleo pulposo, central e gelatinoso. O disco também se relaciona com placas terminais cartilaginosas dos corpos vertebrais.',
        cue: 'No modelo “jelly donut” da Universidade de Wisconsin: massa por fora = anel; recheio por dentro = núcleo. “Pulposo” lembra polpa.',
        kind: 'Analogia universitária documentada', diagram: 'disc',
        trap: 'O núcleo é tecido gelatinoso rico em água, não um reservatório de líquido sinovial. Não há disco entre atlas e áxis.',
        sources: ['spine', 'donut'] },
      { id: 'sinfise', title: 'Sínfise púbica: união da frente da pelve',
        answer: 'É a articulação cartilaginosa entre os púbis direito e esquerdo, na linha mediana anterior da pelve. Possui disco interposto de fibrocartilagem e permite pequenos movimentos.',
        cue: 'Ache o púbis dos dois lados; o encontro no meio é a sínfise púbica.',
        kind: 'Localização', trap: 'Sínfise não é sinovial nem sinostose. Sinostose é união por osso. A grafia é sínfise.',
        sources: ['cartilage'] },
      { id: 'cruzados', title: 'LCA e LCP: comece pela tíbia',
        cue: 'A de anterior: fixa na frente da tíbia e freia a tíbia indo para a frente. P de posterior: fixa atrás e freia a tíbia indo para trás. Sempre imagine o fêmur parado.',
        kind: 'Nome + movimento', diagram: 'cruciates',
        comparison: { headers: ['O que comparar', 'LCA', 'LCP'], rows: [
          ['Fixação na tíbia', 'Área anterior', 'Área posterior'],
          ['Fixação no fêmur', 'Lado lateral (face interna)', 'Lado medial (face interna)'],
          ['Movimento que limita', 'Tíbia para a frente em relação ao fêmur', 'Tíbia para trás em relação ao fêmur'],
        ] },
        recognition: [
          'Ache a frente do joelho pela patela ou pela tuberosidade da tíbia.',
          'Localize a fixação tibial de cada faixa.',
          'Siga a faixa até o fêmur: LCA chega ao lado lateral; LCP, ao medial. Não decida só pelo cruzamento em X.',
        ],
        trap: 'O nome usa a tíbia como referência, não a posição da faixa na foto nem o côndilo do fêmur. Se trocar o osso que se move, a direção se inverte: tíbia para a frente equivale a fêmur para trás. “Face medial do côndilo lateral” é a parede interna desse côndilo, não o côndilo medial.',
        sources: ['knee', 'acl', 'pcl'] },
      { id: 'menisco', title: 'Meniscos: dois calços de fibrocartilagem',
        answer: 'Meniscos são estruturas de fibrocartilagem entre fêmur e tíbia. Ajudam a distribuir carga, absorver impactos e melhorar o encaixe das superfícies. Há um medial e um lateral em cada joelho.',
        cue: 'Medial parece um C mais aberto; lateral parece um anel quase fechado, um O incompleto.',
        kind: 'Forma', diagram: 'menisci',
        trap: 'Menisco não é ligamento. O “O” lateral não é um círculo totalmente fechado; as formas variam.',
        sources: ['menisci'] },
    ] },
  { id: 'musculos', title: 'Músculos e tendão calcâneo',
    intro: 'Combine nome, posição e ação. Na prova, diga o nome completo da estrutura.',
    tips: [
      { id: 'calcaneo', title: 'Tendão calcâneo: destino, calcanhar',
        answer: 'O tendão calcâneo, também conhecido como tendão de Aquiles, prende principalmente gastrocnêmio e sóleo ao calcâneo, o osso do calcanhar. Fica na parte posterior do tornozelo.',
        cue: 'Calcâneo → calcanhar. A história do “calcanhar de Aquiles” ajuda a lembrar o outro nome.',
        kind: 'Nome + referência cultural',
        recognition: 'É a faixa resistente atrás do tornozelo, acima do calcanhar. Transmite a força da panturrilha na flexão plantar, como ao ficar na ponta dos pés.',
        trap: 'Tendão une músculo a osso; ligamento geralmente une osso a osso. Use “tendão calcâneo” na resposta anatômica.',
        sources: ['legMuscles'] },
      { id: 'masseter', title: 'Masseter: sinta o músculo da mastigação',
        answer: 'O masseter vai do arco zigomático à face lateral do ramo e do ângulo da mandíbula. Sua ação principal é elevar a mandíbula, fechando a boca.',
        cue: 'Coloque os dedos junto ao ângulo da mandíbula e cerre os dentes levemente: o músculo endurece. Masseter e mastigação têm relação com a ideia de mastigar.',
        kind: 'Gesto + função',
        recognition: 'Masseter: lateral da mandíbula. Temporal: acima do arco zigomático, em leque na região da têmpora. Ambos participam da mastigação.',
        trap: 'Não confunda com bucinador, que comprime a bochecha e ajuda a manter o alimento entre os dentes.',
        sources: ['headMuscles'] },
      { id: 'vasto-reto', title: 'Quadríceps: um reto e três vastos',
        answer: 'Reto femoral é superficial, na frente e no centro da coxa. Vasto lateral fica para fora; vasto medial, para dentro; vasto intermédio fica profundo ao reto femoral, sobre o fêmur.',
        cue: 'Lateral e medial dão o endereço. Intermédio fica escondido atrás do reto: levante o reto para vê-lo.',
        kind: 'Camadas + posição', diagram: 'quadriceps',
        recognition: 'Os quatro estendem o joelho. O reto femoral cruza quadril e joelho, ajudando também a flexionar o quadril; os vastos se originam no fêmur e cruzam só o joelho.',
        trap: '“Vasto” significa amplo; “reto” remete à direção. São nomes usados em outros músculos também. Aqui a comparação é entre os quatro componentes do quadríceps femoral.',
        sources: ['legMuscles'] },
    ] },
];
