export type Source = { label: string; url?: string };
const book = 'https://openstax.org/books/anatomy-and-physiology-2e/pages/';
export const sources: Record<string, Source> = {
  terms: { label: 'OpenStax · Terminologia anatômica', url: book + '1-6-anatomical-terminology' },
  skull: { label: 'OpenStax · Crânio', url: book + '7-2-the-skull' },
  spine: { label: 'OpenStax · Coluna vertebral', url: book + '7-3-the-vertebral-column' },
  sternum: { label: 'Kenhub · Esterno', url: 'https://www.kenhub.com/en/library/anatomy/sternum' },
  arm: { label: 'OpenStax · Ossos do membro superior', url: book + '8-2-bones-of-the-upper-limb' },
  pelvis: { label: 'OpenStax · Cintura pélvica', url: book + '8-3-the-pelvic-girdle-and-pelvis' },
  fibrous: { label: 'OpenStax · Articulações fibrosas', url: book + '9-2-fibrous-joints' },
  cartilage: { label: 'OpenStax · Articulações cartilaginosas', url: book + '9-3-cartilaginous-joints' },
  synovial: { label: 'OpenStax · Articulações sinoviais', url: book + '9-4-synovial-joints' },
  knee: { label: 'OpenStax · Articulações selecionadas', url: book + '9-6-anatomy-of-selected-synovial-joints' },
  acl: { label: 'Kenhub · Ligamento cruzado anterior',
    url: 'https://www.kenhub.com/en/library/anatomy/anterior-cruciate-ligament' },
  pcl: { label: 'Kenhub · Ligamento cruzado posterior',
    url: 'https://www.kenhub.com/en/library/anatomy/posterior-cruciate-ligament' },
  menisci: { label: 'Kenhub · Meniscos', url: 'https://www.kenhub.com/en/library/anatomy/the-knee-joint' },
  headMuscles: { label: 'OpenStax · Músculos da cabeça', url: book + '11-3-axial-muscles-of-the-head-neck-and-back' },
  legMuscles: { label: 'OpenStax · Músculos do membro inferior', url: book + '11-6-appendicular-muscles-of-the-pelvic-girdle-and-lower-limbs' },
  brain: { label: 'OpenStax · Sistema nervoso central', url: book + '13-2-the-central-nervous-system' },
  meninges: { label: 'Kenhub · Meninges', url: 'https://www.kenhub.com/en/library/anatomy/meninges-of-the-brain-and-spinal-cord' },
  pad: { label: 'UC San Diego · Macete PAD, COGS 17', url: 'https://pages.ucsd.edu/~johnson/COGS17/17Mnemonics.html' },
  padLayers: { label: "Universidade de Washington · Meninges PAD the brain",
    url: "https://staff.washington.edu/chudler/cover.html" },
  donut: { label: 'Universidade de Wisconsin · Jelly Donut Model', url: 'https://radiology.wisc.edu/wp-content/uploads/2017/12/Schreibman_LSpineImaging-2_Handout.pdf' },
  yes: { label: 'Kenhub · Articulação atlanto-occipital', url: 'https://www.kenhub.com/en/library/anatomy/atlanto-occipital-joint' },
  no: { label: 'Kenhub · Articulação atlantoaxial', url: 'https://www.kenhub.com/en/library/anatomy/atlantoaxial-joint' },
  thumb: { label: 'Relato de aluno · O gesto “All right, radius!”', url: 'https://www.reddit.com/r/medicalschool/comments/zxeaun/' },
};
