import type { Question } from "./questions";

export type AnatomyExplanation = {
  title: string;
  text: string;
};

type ReviewTopic = AnatomyExplanation & { items: number[] };

// Sínteses didáticas dos materiais de 2026-2 do professor Erivelto Luís Chacon.
// Os itens remetem ao roteiro unificado da P1; o texto também usa as relações
// anatômicas apresentadas nas peças e nas ilustrações das aulas práticas.
const REVIEW_TOPICS: ReviewTopic[] = [
  { items: [1], title: "Frontal: neurocrânio e testa",
    text: "O osso frontal ocupa a região anterior do crânio e forma a testa. Pertence ao neurocrânio, a parte óssea que protege o encéfalo. Seu encontro com os parietais forma a sutura coronal, também chamada frontoparietal." },
  { items: [2], title: "Parietais: teto e paredes do crânio",
    text: "Os parietais são dois ossos do neurocrânio, um de cada lado. Participam do teto e das paredes laterais do crânio. A linha de união entre eles é a sutura sagital ou interparietal; anteriormente, encontram o frontal na sutura coronal." },
  { items: [3], title: "Temporal: osso e músculo são estruturas diferentes",
    text: "Os ossos temporais são pares e ficam nas regiões laterais do neurocrânio. A mandíbula se articula com eles nas articulações temporomandibulares. O músculo temporal ocupa a região das têmporas, mas não é o osso temporal: observe qual tipo de estrutura a pergunta pede." },
  { items: [4, 5], title: "Occipital e forame magno",
    text: "O osso occipital forma parte da região posterior e da base do neurocrânio. Nele fica o forame magno, uma abertura pela qual ocorre a continuidade entre o bulbo e a medula espinal. Diferencie o osso inteiro, occipital, de seu acidente anatômico, o forame magno." },
  { items: [6], title: "Nasais: ponte óssea do nariz",
    text: "Os ossos nasais são pares e participam da ponte óssea do nariz. Pertencem ao viscerocrânio, o esqueleto da face. Para reconhecer a peça, procure a região superior do nariz; a parte inferior do nariz também possui cartilagens." },
  { items: [7], title: "Maxila: dentes superiores",
    text: "As maxilas são ossos pares do viscerocrânio e contêm os alvéolos dos dentes superiores. A mandíbula contém os alvéolos inferiores. Essa relação ajuda a distinguir as duas estruturas: maxila na região superior da boca e mandíbula na inferior." },
  { items: [8], title: "Zigomático: maçã do rosto",
    text: "O osso zigomático é um osso par do viscerocrânio que forma a saliência da maçã do rosto. Localize-o lateralmente à maxila e à órbita. A testa corresponde ao frontal; a maçã do rosto, ao zigomático." },
  { items: [9], title: "Mandíbula: região inferior da face",
    text: "A mandíbula é um osso ímpar do viscerocrânio e contém os alvéolos dos dentes inferiores. Articula-se com os ossos temporais e se movimenta durante a mastigação. Não confunda a mandíbula com a maxila, que sustenta os dentes superiores." },
  { items: [10], title: "Esterno: três partes em sequência",
    text: "O esterno fica na região anterior do tórax. De cima para baixo, suas partes são manúbrio, corpo e processo xifoide. O manúbrio se articula com as clavículas; o corpo é a porção intermediária e mais longa; o processo xifoide é a porção inferior." },
  { items: [11, 12], title: "Atlas e áxis: C1 e C2",
    text: "A vértebra cervical atlas é C1, a primeira cervical, e se articula com o crânio. A vértebra cervical áxis é C2, a segunda, reconhecida pelo dente do áxis. Para diferenciar as peças, procure o formato de anel do atlas e a projeção óssea característica do áxis." },
  { items: [13], title: "C7: vértebra proeminente",
    text: "C7 é a sétima vértebra cervical, chamada proeminente por seu processo espinhoso longo. Ela pertence à região cervical, que possui sete vértebras. Na peça, observe a projeção posterior e diferencie C7 do atlas (C1) e do áxis (C2)." },
  { items: [14], title: "Reconhecendo uma cervical típica",
    text: "Uma vértebra cervical típica apresenta forames transversários nos processos transversos. Esse detalhe ajuda a distingui-la das vértebras torácicas e lombares. Atlas, áxis e C7 têm características próprias; C4 é o exemplo de cervical típica usado no modelo do site." },
  { items: [15], title: "Torácicas: relação com as costelas",
    text: "A região torácica possui doze vértebras. As vértebras torácicas apresentam superfícies articulares para as costelas, uma característica útil para reconhecer a peça. Elas fazem parte do esqueleto axial e, com as costelas e o esterno, compõem a estrutura óssea do tórax." },
  { items: [16], title: "Lombares: sustentação",
    text: "A região lombar possui cinco vértebras. Seus corpos vertebrais são volumosos, relacionados à sustentação do peso corporal. Na comparação das peças, diferencie esse corpo grande dos forames transversários das cervicais e das superfícies para costelas das torácicas." },
  { items: [17, 18], title: "Sacro e cóccix: vértebras fundidas",
    text: "O sacro resulta da fusão de cinco vértebras sacrais e participa da pelve óssea. O cóccix fica inferiormente ao sacro, na extremidade da coluna. Geralmente, o cóccix possui quatro vértebras coccígeas fundidas, mas o número pode variar. Não confunda essas peças com vértebras lombares isoladas." },
  { items: [19, 20, 21], title: "Clavícula e escápula: cintura escapular",
    text: "Clavícula e escápula compõem a cintura escapular. A clavícula liga o esterno ao acrômio da escápula. Na face posterior da escápula, a espinha separa as fossas supraespinal e infraespinal e continua lateralmente no acrômio. A cavidade glenoidal recebe a cabeça do úmero." },
  { items: [22, 23], title: "Úmero: osso do braço",
    text: "O braço é o segmento entre ombro e cotovelo e possui um osso, o úmero. Sua cabeça fica na extremidade proximal e se articula com a cavidade glenoidal da escápula. Rádio e ulna pertencem ao antebraço, não ao braço." },
  { items: [24, 25], title: "Rádio e ulna na posição anatômica",
    text: "Na posição anatômica, com as palmas voltadas para a frente, o rádio fica lateralmente, do lado do polegar; a ulna fica medialmente, do lado do dedo mínimo. Medial significa mais próximo do plano mediano do corpo; lateral, mais afastado. Use essa posição como referência, mesmo que a peça esteja girada." },
  { items: [26], title: "Osso do quadril e pelve óssea",
    text: "Cada osso do quadril é formado pela união de ílio, ísquio e púbis. Os dois ossos do quadril, junto ao sacro, participam da pelve óssea. Anteriormente, os púbis se unem na sínfise púbica; lateralmente, o acetábulo recebe a cabeça do fêmur." },
  { items: [27, 28], title: "Fêmur: osso da coxa",
    text: "O fêmur é o osso longo da coxa. Sua cabeça fica na extremidade proximal e se articula com o acetábulo do osso do quadril, formando a articulação coxofemoral. Diferencie coxa, com o fêmur, de perna, com tíbia e fíbula." },
  { items: [29], title: "Patela: anterior ao joelho",
    text: "A patela é um osso sesamoide localizado no tendão do quadríceps, anteriormente ao joelho. Os meniscos são estruturas fibrocartilagíneas dentro da articulação, entre fêmur e tíbia. Assim, patela e menisco diferem tanto na localização quanto no tipo de tecido." },
  { items: [30, 31], title: "Tíbia e fíbula: medial e lateral",
    text: "Na perna, a tíbia fica medialmente, mais próxima do plano mediano, e a fíbula fica lateralmente. A tíbia é o osso mais volumoso e participa da articulação com o fêmur no joelho. Ao girar a peça, mantenha como referência os lados anatômicos, não a direita e a esquerda da tela." },
  { items: [32, 33, 34], title: "Suturas: observe quais ossos se encontram",
    text: "As suturas são articulações fibrosas do crânio. A sagital ou interparietal une os dois parietais; a coronal ou frontoparietal une frontal e parietais; a lambdóidea ou parietoccipital une parietais e occipital. Os nomes alternativos ajudam a lembrar os ossos envolvidos." },
  { items: [35], title: "Gonfose: dente e alvéolo",
    text: "A gonfose é uma articulação fibrosa entre a raiz do dente e seu alvéolo na maxila ou na mandíbula. A fixação ocorre por tecido fibroso do ligamento periodontal. Diferencie gonfose, relacionada aos dentes, de sutura, que une ossos do crânio. Dentes não são ossos." },
  { items: [36, 37], title: "Sindesmose: membrana interóssea",
    text: "Nas sindesmoses, tecido conjuntivo fibroso une peças ósseas. A radioulnar envolve a membrana interóssea entre rádio e ulna, no antebraço; a tibiofibular envolve a membrana entre tíbia e fíbula, na perna. O nome da articulação indica os ossos que ela conecta." },
  { items: [38], title: "Disco intervertebral: anel e núcleo",
    text: "O disco intervertebral fica entre os corpos das vértebras e participa de uma articulação cartilagínea do tipo sínfise. É constituído por anel fibroso periférico e núcleo pulposo central. Diferencie o disco inteiro de cada componente: anel e núcleo juntos formam o disco." },
  { items: [39], title: "Sínfise púbica: união anterior da pelve",
    text: "A sínfise púbica une os púbis direito e esquerdo na região anterior da pelve. É uma articulação cartilagínea com fibrocartilagem interposta. A articulação coxofemoral fica lateralmente, entre fêmur e osso do quadril, e é sinovial: são articulações diferentes." },
  { items: [40], title: "Ombro: articulação glenoumeral",
    text: "A cabeça do úmero se articula com a cavidade glenoidal da escápula. Essa articulação do ombro é chamada glenoumeral e é sinovial. As articulações sinoviais possuem cápsula, cartilagem articular e líquido sinovial e permitem movimentos amplos." },
  { items: [41], title: "Cotovelo: encontro do braço com o antebraço",
    text: "O complexo articular do cotovelo reúne úmero, ulna e rádio. Inclui as articulações umeroulnar, umerorradial e radioulnar proximal. O úmero pertence ao braço; rádio e ulna, ao antebraço. São articulações sinoviais, diferentes da sindesmose interóssea entre rádio e ulna." },
  { items: [42], title: "Quadril: articulação coxofemoral",
    text: "A cabeça do fêmur se articula com o acetábulo do osso do quadril. Articulação do quadril e articulação coxofemoral são nomes para essa articulação sinovial. Não a confunda com a sínfise púbica, que une os dois púbis anteriormente." },
  { items: [43, 45], title: "Ligamentos cruzados: LCA e LCP",
    text: "LCA significa ligamento cruzado anterior; LCP, ligamento cruzado posterior. Ambos são ligamentos intracapsulares do joelho e ajudam na estabilidade articular. Ligamentos são estruturas de tecido conjuntivo denso; meniscos são fibrocartilagens que complementam as superfícies articulares." },
  { items: [44, 46], title: "Meniscos: lado medial e lado lateral",
    text: "Os meniscos são estruturas fibrocartilagíneas entre fêmur e tíbia que complementam as superfícies articulares do joelho. O medial fica do lado voltado para o plano mediano; o lateral, do lado da fíbula. Não são ossos nem ligamentos cruzados." },
  { items: [47, 48], title: "Temporal e masseter: mastigação",
    text: "Temporal e masseter são músculos da mastigação. O temporal ocupa a região das têmporas; o masseter fica na região lateral da mandíbula. Para diferenciá-los, use a localização: lateral do crânio para o temporal e lateral da mandíbula para o masseter." },
  { items: [49], title: "Diafragma: tórax e abdome",
    text: "O músculo diafragma separa as cavidades torácica e abdominal e participa da respiração. Diferencie essa separação interna dos músculos da parede abdominal, como o reto do abdome. O diafragma é um músculo ímpar e mediano." },
  { items: [50], title: "Reto do abdome: parede anterior",
    text: "O músculo reto do abdome fica na parede anterior do abdome. Seu aspecto segmentado resulta das interseções tendíneas. Diferencie essa posição anterior das camadas laterais da parede abdominal, formadas por oblíquo externo, oblíquo interno e transverso do abdome." },
  { items: [51, 52, 53], title: "Parede lateral do abdome: ordem das camadas",
    text: "Da camada mais superficial para a mais profunda, a sequência é oblíquo externo, oblíquo interno e transverso do abdome. O oblíquo interno fica entre os outros dois. Quando a pergunta indicar profundidade, use essa ordem para reconhecer o músculo solicitado." },
  { items: [54], title: "Supraespinal: acima da espinha da escápula",
    text: "O músculo supraespinal ocupa a fossa supraespinal, acima da espinha da escápula. Ele integra o manguito rotador com infraespinal, redondo menor e subescapular. A espinha é uma referência óssea útil para separar supraespinal e infraespinal na peça." },
  { items: [55], title: "Infraespinal: abaixo da espinha da escápula",
    text: "O músculo infraespinal ocupa a fossa infraespinal, abaixo da espinha da escápula, na face posterior. Faz parte do manguito rotador. Diferencie-o do supraespinal, situado acima da espinha, e do subescapular, na face anterior da escápula." },
  { items: [56], title: "Redondo menor: integrante do manguito",
    text: "O músculo redondo menor fica na região posterior do ombro, próximo à margem lateral da escápula. Ele integra o manguito rotador, junto a supraespinal, infraespinal e subescapular. O redondo maior e o deltoide não entram nessa lista de quatro músculos." },
  { items: [57], title: "Subescapular: face anterior da escápula",
    text: "O músculo subescapular ocupa a fossa subescapular, na face anterior da escápula, voltada para o tórax. É um dos quatro músculos do manguito rotador. Na peça, diferencie essa face da posterior, onde ficam a espinha, o supraespinal e o infraespinal." },
  { items: [58], title: "Deltoide: músculo que recobre o ombro",
    text: "O deltoide tem partes clavicular, acromial e espinal, relacionadas à clavícula, ao acrômio e à espinha da escápula. A parte acromial participa da abdução do braço; as outras partes participam de movimentos de flexão, extensão e rotação. Ele recobre o ombro, mas não integra o manguito rotador." },
  { items: [59, 60], title: "Bíceps e tríceps: faces do braço",
    text: "O bíceps braquial ocupa a região anterior do braço e participa da flexão do cotovelo. O tríceps braquial fica posteriormente e participa da extensão. Os nomes também indicam suas cabeças: duas no bíceps e três no tríceps. Compare a face da peça antes de nomear o músculo." },
  { items: [61], title: "Vasto lateral: lado lateral da coxa",
    text: "O músculo vasto lateral integra o quadríceps femoral e ocupa o lado lateral da região anterior da coxa. Diferencie-o do vasto medial, do lado voltado para o plano mediano, e do vasto intermédio, que fica profundo ao reto femoral." },
  { items: [62], title: "Vasto intermédio: profundo ao reto femoral",
    text: "O músculo vasto intermédio é um componente do quadríceps femoral situado profundamente ao reto femoral. Por isso, o site usa uma camada com o reto femoral removido para expô-lo. Vasto intermédio e reto femoral são músculos distintos, embora um recubra o outro." },
  { items: [63], title: "Vasto medial: lado medial da coxa",
    text: "O músculo vasto medial integra o quadríceps e fica no lado medial da região anterior da coxa, próximo ao joelho. Medial significa voltado para o plano mediano do corpo. Não use apenas o lado da tela: o modelo pode estar girado." },
  { items: [64], title: "Reto femoral: componente superficial do quadríceps",
    text: "O reto femoral fica superficialmente ao vasto intermédio na região anterior da coxa. O quadríceps femoral é formado por reto femoral, vasto lateral, vasto medial e vasto intermédio. Os quatro componentes convergem para o tendão do quadríceps, que se insere na patela." },
  { items: [65], title: "Glúteo máximo: região posterior do quadril",
    text: "O glúteo máximo é um músculo volumoso da região posterior do quadril, superficial aos glúteos médio e mínimo. A musculatura glútea ocupa uma região diferente dos músculos anteriores da coxa, como o quadríceps. Use a região e a profundidade para reconhecer a peça." },
  { items: [66, 67, 68], title: "Panturrilha: gastrocnêmio, sóleo e tendão",
    text: "O gastrocnêmio possui cabeças medial e lateral e fica superficial ao sóleo. Juntos, eles formam o tríceps sural e convergem para o tendão do calcâneo, inserido no calcâneo. O tendão transmite a força da contração; não é o ventre muscular. Na peça preparada, as cabeças do gastrocnêmio são afastadas para expor parte do sóleo." },
  { items: [69, 70], title: "Meninges: da superfície para a profundidade",
    text: "A sequência das meninges é dura-máter, aracnoide-máter e pia-máter. A dura-máter é a mais externa; a pia-máter acompanha a superfície do tecido nervoso. Aracnoide e pia, em conjunto, formam a leptomeninge. O líquido cerebrospinal ocupa o espaço subaracnóideo, entre aracnoide e pia." },
  { items: [71], title: "Medula espinal: parte do SNC",
    text: "A medula espinal ocupa o canal vertebral e se continua superiormente com o bulbo, na região do forame magno. Trinta e um pares de nervos espinais se conectam a ela por raízes. Diferencie a medula, que pertence ao SNC, dos nervos espinais, que pertencem ao SNP." },
  { items: [72, 73, 74], title: "Tronco encefálico: três componentes",
    text: "De cima para baixo, o tronco encefálico apresenta mesencéfalo, ponte e bulbo. Situa-se entre o diencéfalo e a medula espinal, anteriormente ao cerebelo. O bulbo se continua com a medula; cerebelo e diencéfalo são outras partes do encéfalo e não entram na lista do tronco." },
  { items: [75], title: "Cerebelo: equilíbrio e coordenação",
    text: "O cerebelo fica posteriormente ao tronco encefálico. Suas funções estão relacionadas ao equilíbrio e à coordenação dos movimentos. Ele possui vérmis e hemisférios cerebelares direito e esquerdo. Não confunda cerebelo com cérebro nem o inclua entre os três componentes do tronco encefálico." },
  { items: [76], title: "Diencéfalo: tálamo e hipotálamo",
    text: "O diencéfalo inclui tálamo, hipotálamo, subtálamo e epitálamo, entre suas subdivisões. O tálamo participa da integração de informações, e o hipotálamo participa da homeostasia, incluindo temperatura, fome e sede. Essas estruturas pertencem ao diencéfalo, não ao tronco encefálico." },
  { items: [77, 78], title: "Fissura longitudinal e corpo caloso",
    text: "A fissura longitudinal separa incompletamente os hemisférios cerebrais direito e esquerdo. O corpo caloso é uma comissura que conecta esses hemisférios e forma o assoalho dessa fissura. Assim, a fissura é a separação visível; o corpo caloso é a estrutura de conexão." },
  { items: [79, 83], title: "Frontal: lobo e polo",
    text: "O lobo frontal ocupa a região anterior do hemisfério, à frente do sulco central. O polo frontal é sua extremidade anterior, não o lobo inteiro. O giro pré-central, relacionado à área motora primária, fica no lobo frontal." },
  { items: [80], title: "Parietal: posterior ao sulco central",
    text: "O lobo parietal fica posteriormente ao sulco central e superiormente ao sulco lateral. Nele fica o giro pós-central, relacionado à sensibilidade somestésica. Use o sulco central para diferenciar frontal, à frente, e parietal, atrás." },
  { items: [81, 84], title: "Temporal: lobo e polo",
    text: "O lobo temporal fica inferiormente ao sulco lateral. Seu polo temporal é a extremidade anterior. Lobo indica uma região mais extensa; polo indica uma extremidade. Cada hemisfério possui os polos frontal, temporal e occipital." },
  { items: [82, 85], title: "Lobo occipital: região posterior do cérebro",
    text: "O lobo occipital ocupa a região posterior do hemisfério cerebral. Frontal, parietal, temporal e occipital são lobos cerebrais, e a ínsula também constitui um lobo, situado profundamente ao sulco lateral. Lobo indica uma região extensa; polo indica uma extremidade do hemisfério." },
  { items: [86, 87, 88], title: "Nervos do membro superior: SNP",
    text: "Radial, mediano e ulnar são nervos periféricos do membro superior, originados do plexo braquial. Nervos são estruturas diferentes dos ossos e músculos que acompanham. O nervo radial está relacionado à musculatura posterior do antebraço, enquanto o nervo mediano atravessa o túnel do carpo." },
  { items: [89, 90, 91, 92], title: "Nervos do membro inferior e ramos do isquiático",
    text: "Femoral, isquiático, tibial e fibular comum são nervos periféricos do membro inferior. O femoral é distinto do isquiático; os nervos tibial e fibular comum são os dois ramos terminais do isquiático. Se a pergunta pedir os ramos terminais, responda tibial e fibular comum, não a lista dos quatro nervos." },
];

const GROUP_REVIEWS: ReviewTopic[] = [
  { items: [1, 2, 3, 4], title: "Neurocrânio e viscerocrânio",
    text: "O neurocrânio forma a caixa óssea que protege o encéfalo. Frontal, parietais, temporais e occipital pertencem a essa divisão, junto ao esfenoide e ao etmoide. O viscerocrânio forma o esqueleto da face e inclui nasais, maxilas, zigomáticos e mandíbula. A lista da pergunta não reúne todos os ossos do neurocrânio." },
  { items: [54, 55, 56, 57], title: "Manguito rotador: quatro músculos",
    text: "O manguito rotador reúne supraespinal, infraespinal, redondo menor e subescapular. Supraespinal e infraespinal ficam acima e abaixo da espinha da escápula; o subescapular fica na face anterior; o redondo menor, próximo à margem lateral. Deltoide e redondo maior não fazem parte desse conjunto." },
  { items: [61, 62, 63, 64], title: "Quadríceps femoral: quatro componentes",
    text: "O quadríceps femoral reúne reto femoral, vasto lateral, vasto medial e vasto intermédio na região anterior da coxa. Lateral e medial indicam os lados; o intermédio fica profundo ao reto femoral. Os quatro componentes possuem origens distintas e convergem para o tendão do quadríceps, que se insere na patela." },
];

export function anatomyReview(question: Pick<Question, "p1Items">): AnatomyExplanation[] {
  const items = question.p1Items ?? [];
  const group = GROUP_REVIEWS.find(topic => topic.items.every(item => items.includes(item)));
  const covered = group?.items ?? [];
  const topics = REVIEW_TOPICS.filter(topic =>
    topic.items.some(item => items.includes(item) && !covered.includes(item)));
  return [...(group ? [group] : []), ...topics].map(({ title, text }) =>
    ({ title, text }));
}
