import type { Category, Question } from "./questions";
import type { ModelId } from "./models";

// Fonte: 09 Roteiro Unificado de Aula Prática — Avaliação (P1), 2026-2.
// Itens ausentes do banco anterior. Cada questão mantém a referência ao roteiro.
function p1Name(
  item: number, category: Category, title: string,
  response: Pick<Question, "answer" | "accepted" | "explanation">,
  visual?: { model: ModelId; highlight: string; isolatedBones?: string[] },
): Question {
  return {
    id: `p1-${item}`, p1Items: [item], category, kind: "name", title,
    instruction: "Responda com o nome anatômico usado no roteiro da P1.",
    ...response, ...visual,
  };
}

export const P1_COMPLEMENT: Question[] = [
  p1Name(2, "skull", "Osso par que forma parte do teto e das paredes laterais do neurocrânio.",
    { answer: "Osso parietal", accepted: [],
      explanation: "Os ossos parietais são pares e se encontram na sutura sagital (interparietal)." },
    { model: "overview-skull-natural", highlight: "Parietal bone" }),
  p1Name(4, "skull", "Osso do neurocrânio que contém o forame magno.",
    { answer: "Osso occipital", accepted: [],
      explanation: "O forame magno é uma abertura do osso occipital na base do crânio." },
    { model: "overview-skull-natural", highlight: "Occipital bone" }),
  p1Name(6, "skull", "Osso par que participa da formação da ponte óssea do nariz.",
    { answer: "Osso nasal", accepted: ["ossos nasais"],
      explanation: "Os ossos nasais pertencem ao viscerocrânio." },
    { model: "overview-skull-natural", highlight: "Nasal bone" }),
  p1Name(7, "skull", "Osso da face que contém os alvéolos dos dentes superiores.",
    { answer: "Osso maxilar", accepted: ["maxila", "osso maxila"],
      explanation: "A maxila pertence ao viscerocrânio e contém os alvéolos dos dentes superiores." },
    { model: "overview-skull-natural", highlight: "Maxilla bone" }),
  p1Name(19, "upper", "Osso que liga o manúbrio do esterno ao acrômio da escápula.",
    { answer: "Clavícula", accepted: ["osso clavícula"],
      explanation: "A clavícula apresenta uma extremidade esternal e uma extremidade acromial." },
    { model: "skeleton-practice", highlight: "clavicle", isolatedBones: ["clavicle"] }),
  p1Name(20, "upper", "Osso plano da cintura escapular que apresenta espinha, acrômio e cavidade glenoidal.",
    { answer: "Escápula", accepted: ["osso escápula"],
      explanation: "A escápula se articula com o úmero por sua cavidade glenoidal." },
    { model: "skeleton-practice", highlight: "Scapula", isolatedBones: ["Scapula"] }),
  p1Name(21, "upper", "Como se chama a saliência óssea da face posterior da escápula que separa as fossas supraespinal e infraespinal?",
    { answer: "Espinha da escápula", accepted: ["espinha escapular"],
      explanation: "A espinha da escápula separa as fossas supraespinal e infraespinal e se continua lateralmente com o acrômio." }),
  p1Name(26, "lower", "Osso formado pela união do ílio, do ísquio e do púbis.",
    { answer: "Osso do quadril", accepted: ["osso coxal"],
      explanation: "Cada osso do quadril é formado pelo ílio, pelo ísquio e pelo púbis." },
    { model: "skeleton-practice", highlight: "Hip bone", isolatedBones: ["Hip bone"] }),
  p1Name(34, "skull", "Sutura entre os ossos parietais e o osso occipital.",
    { answer: "Sutura lambdóidea", accepted: ["sutura parietoccipital", "sutura parieto-occipital", "sutura lambdoide"],
      explanation: "Essa articulação fibrosa é chamada sutura lambdóidea ou parietoccipital." }),
  p1Name(35, "skull", "Como se chamam as articulações fibrosas entre os dentes e seus alvéolos na maxila e na mandíbula?",
    { answer: "Gonfoses maxilares e mandibulares", accepted: ["gonfoses", "gonfose", "articulações dentoalveolares", "gonfoses dentoalveolares"],
      explanation: "Nas gonfoses, as raízes dos dentes se fixam aos alvéolos pelo ligamento periodontal. Dentes não são ossos." }),
  p1Name(36, "upper", "Articulação fibrosa constituída pela membrana interóssea entre rádio e ulna.",
    { answer: "Sindesmose radioulnar", accepted: ["sindesmose rádio-ulnar", "membrana interóssea radioulnar", "membrana interóssea do antebraço"],
      explanation: "A sindesmose radioulnar envolve a membrana interóssea entre os ossos do antebraço." }),
  p1Name(37, "lower", "Articulação fibrosa constituída pela membrana interóssea entre tíbia e fíbula.",
    { answer: "Sindesmose tibiofibular", accepted: ["sindesmose tíbio-fibular", "membrana interóssea tibiofibular", "membrana interóssea da perna"],
      explanation: "A sindesmose tibiofibular envolve a membrana interóssea entre os ossos da perna." }),
  p1Name(40, "upper", "Articulação sinovial entre a cabeça do úmero e a cavidade glenoidal da escápula.",
    { answer: "Articulação do ombro", accepted: ["articulação glenoumeral", "articulação escapuloumeral"],
      explanation: "A articulação glenoumeral é a articulação entre a cabeça do úmero e a cavidade glenoidal da escápula." }),
  p1Name(41, "upper", "Como se chama o conjunto articular sinovial da região em que o braço se encontra com o antebraço?",
    { answer: "Articulação do cotovelo", accepted: ["cotovelo"],
      explanation: "O complexo articular do cotovelo inclui as articulações umeroulnar, umerorradial e radioulnar proximal." }),
  p1Name(46, "lower", "Estrutura fibrocartilagínea do joelho situada do lado da fíbula.",
    { answer: "Menisco lateral", accepted: [],
      explanation: "O menisco lateral ocupa o compartimento lateral do joelho; o menisco medial ocupa o compartimento medial." }),
  p1Name(51, "abdomen", "Músculo da camada superficial da parede lateral do abdome, superficial ao oblíquo interno.",
    { answer: "Músculo oblíquo externo do abdome", accepted: ["músculo oblíquo externo abdominal"],
      explanation: "Na parede lateral do abdome, o oblíquo externo é superficial ao oblíquo interno e ao transverso do abdome." }),
  p1Name(52, "abdomen", "Músculo da parede lateral do abdome situado entre o oblíquo externo e o transverso do abdome.",
    { answer: "Músculo oblíquo interno do abdome", accepted: ["músculo oblíquo interno abdominal"],
      explanation: "O oblíquo interno ocupa a camada intermediária entre o oblíquo externo e o transverso do abdome." }),
  p1Name(53, "abdomen", "Músculo mais profundo das três camadas musculares da parede lateral do abdome.",
    { answer: "Músculo transverso do abdome", accepted: ["músculo transverso abdominal"],
      explanation: "O transverso do abdome está profundo aos músculos oblíquos externo e interno." }),
  p1Name(58, "upper", "Músculo superficial que recobre o ombro, com partes clavicular, acromial e espinal.",
    { answer: "Músculo deltoide", accepted: [],
      explanation: "O deltoide recobre o ombro. Não é um dos quatro músculos do manguito rotador." }),
  p1Name(65, "lower", "Músculo superficial e volumoso da região glútea, superficial aos glúteos médio e mínimo.",
    { answer: "Músculo glúteo máximo", accepted: [],
      explanation: "O glúteo máximo ocupa a camada superficial da região glútea." }),
  p1Name(69, "nervous", "Meninge mais externa que reveste o encéfalo.",
    { answer: "Dura-máter encefálica", accepted: ["dura-máter", "dura mater", "dura mater encefálica"],
      explanation: "A dura-máter é a meninge mais externa. A dura-máter encefálica reveste o encéfalo." }),
  p1Name(71, "nervous", "Parte do sistema nervoso central situada no canal vertebral, contínua superiormente com o bulbo.",
    { answer: "Medula espinal", accepted: ["medula espinhal"],
      explanation: "A medula espinal pertence ao SNC e se continua superiormente com o bulbo." }),
  p1Name(75, "nervous", "Estrutura do SNC situada posteriormente à ponte e ao bulbo e relacionada à coordenação motora e ao equilíbrio.",
    { answer: "Cerebelo", accepted: [],
      explanation: "O cerebelo é uma estrutura distinta do tronco encefálico. Os componentes do tronco são mesencéfalo, ponte e bulbo." }),
  p1Name(76, "nervous", "Divisão do encéfalo que inclui o tálamo e o hipotálamo.",
    { answer: "Diencéfalo", accepted: [],
      explanation: "O tálamo e o hipotálamo são estruturas do diencéfalo; não são componentes do tronco encefálico." }),
  p1Name(77, "nervous", "Fissura que separa os hemisférios cerebrais direito e esquerdo.",
    { answer: "Fissura longitudinal do cérebro", accepted: ["fissura longitudinal cerebral", "fissura inter-hemisférica", "fissura interhemisférica"],
      explanation: "A fissura longitudinal separa os hemisférios, que permanecem conectados por comissuras, entre elas o corpo caloso." }),
  p1Name(79, "nervous", "Lobo cerebral situado anteriormente ao sulco central.",
    { answer: "Lobo frontal", accepted: [],
      explanation: "O lobo frontal está anteriormente ao sulco central. Lobo e polo frontal não são sinônimos." }),
  p1Name(80, "nervous", "Lobo cerebral situado posteriormente ao sulco central e superiormente ao sulco lateral.",
    { answer: "Lobo parietal", accepted: [],
      explanation: "O lobo parietal está posterior ao sulco central e superior ao sulco lateral." }),
  p1Name(81, "nervous", "Lobo cerebral situado inferiormente ao sulco lateral.",
    { answer: "Lobo temporal", accepted: [],
      explanation: "O lobo temporal ocupa a região inferior ao sulco lateral. O polo temporal é sua extremidade anterior." }),
  p1Name(83, "nervous", "Como se chama a extremidade anterior do lobo frontal?",
    { answer: "Polo frontal", accepted: [],
      explanation: "O polo frontal é a extremidade anterior do lobo frontal; o termo não designa todo o lobo." }),
  p1Name(84, "nervous", "Como se chama a extremidade anterior do lobo temporal?",
    { answer: "Polo temporal", accepted: [],
      explanation: "O polo temporal é a extremidade anterior do lobo temporal; o termo não designa todo o lobo." }),
  {
    id: "p1-10-xifoide", p1Items: [10], category: "thorax", kind: "name",
    title: "Como se chama a parte inferior do esterno?",
    instruction: "Responda com o nome anatômico usado no roteiro da P1.",
    answer: "Processo xifoide", accepted: ["apêndice xifoide"], incompleteAccepted: ["xifoide"],
    explanation: "O esterno se divide em manúbrio, corpo e processo xifoide. O processo xifoide é sua porção inferior.",
  },
  {
    id: "p1-26-componentes", p1Items: [26], category: "lower", kind: "complete",
    title: "Cada osso do quadril é formado pelo ____, pelo ____ e pelo ____.",
    instruction: "Preencha as três lacunas. A ordem dos componentes pode variar.",
    answer: "Ílio; ísquio; púbis", accepted: [], unorderedGroups: true,
    answerGroups: [["ílio", "osso ílio"], ["ísquio", "osso ísquio"], ["púbis", "osso púbis"]],
    explanation: "Ílio, ísquio e púbis se unem para formar cada osso do quadril.",
  },
  {
    id: "p1-10-partes", p1Items: [10], category: "thorax", kind: "complete",
    title: "As três partes do esterno são ____, ____ e ____.",
    instruction: "Escreva os nomes das três partes. A ordem pode variar.",
    answer: "Manúbrio do esterno; corpo do esterno; processo xifoide", accepted: [], unorderedGroups: true,
    answerGroups: [["manúbrio do esterno", "manúbrio esternal", "manúbrio"],
      ["corpo do esterno", "corpo esternal"], ["processo xifoide", "apêndice xifoide"]],
    explanation: "O manúbrio é superior, o corpo é intermediário e o processo xifoide é inferior.",
  },
  {
    id: "p1-70-meninges", p1Items: [70], category: "nervous", kind: "complete",
    title: "As duas meninges que, em conjunto, constituem a leptomeninge são ____ e ____.",
    instruction: "Nomeie as duas meninges. A ordem pode variar.",
    answer: "Aracnoide-máter; pia-máter", accepted: [], unorderedGroups: true,
    answerGroups: [["aracnoide-máter", "aracnoide mater", "aracnoide"], ["pia-máter", "pia mater"]],
    explanation: "Aracnoide-máter e pia-máter formam a leptomeninge (pia-aracnoide). A dura-máter é a meninge externa.",
  },
  {
    id: "p1-86-nervos", p1Items: [86, 87, 88], category: "upper", kind: "complete",
    title: "Os três nervos do membro superior pedidos no roteiro da P1 são ____, ____ e ____.",
    instruction: "Escreva os nomes completos, incluindo “nervo”. A ordem pode variar.",
    answer: "Nervo radial; nervo mediano; nervo ulnar", accepted: [], unorderedGroups: true,
    answerGroups: [["nervo radial"], ["nervo mediano"], ["nervo ulnar"]],
    incompleteAnswerGroups: [["radial"], ["mediano"], ["ulnar"]],
    explanation: "Os nervos radial, mediano e ulnar pertencem ao membro superior.",
  },
  {
    id: "p1-89-nervos", p1Items: [89, 90, 91, 92], category: "lower", kind: "complete",
    title: "Os quatro nervos do membro inferior pedidos no roteiro da P1 são ____, ____, ____ e ____.",
    instruction: "Escreva os nomes completos, incluindo “nervo”. A ordem pode variar.",
    answer: "Nervo femoral; nervo isquiático; nervo tibial; nervo fibular comum", accepted: [], unorderedGroups: true,
    answerGroups: [["nervo femoral"], ["nervo isquiático", "nervo ciático"], ["nervo tibial"],
      ["nervo fibular comum", "nervo peroneal comum"]],
    incompleteAnswerGroups: [["femoral"], ["isquiático", "ciático"], ["tibial"], ["fibular comum", "peroneal comum"]],
    explanation: "Femoral, isquiático, tibial e fibular comum são nervos do membro inferior. O isquiático se divide nos nervos tibial e fibular comum.",
  },
];
